runtime: nodejs
env: flexible

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1

beta_settings:
  # Should be set to environment variable for DB_INSTANCE_CONNECTION_NAME
  cloud_sql_instances: amp-test-cases:us-central1:amp-test-results
