name: GitHub Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'ampproject/amphtml'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: node build-system/pr-check.js
