name: GitHub Actions
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: github.repository == 'ampproject/amp-github-apps'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
      - name: Get npm cache directory
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node-
      - name: Install dependencies
        run: npm ci
      - name: Build and test
        run: node build-system/pr-check.js
        env:
          LOG_LEVEL: warn
